/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    pages: Page;
    blog: Blog;
    portfolio: Portfolio;
    services: Service;
    team: Team;
    clients: Client;
    timeline: Timeline;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    blog: BlogSelect<false> | BlogSelect<true>;
    portfolio: PortfolioSelect<false> | PortfolioSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    timeline: TimelineSelect<false> | TimelineSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  role: 'admin' | 'editor';
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title_en: string;
  title_ar: string;
  /**
   * URL-friendly identifier (e.g., "home", "about", "contact")
   */
  slug: string;
  status: 'draft' | 'published';
  hero?: {
    heading_en?: string | null;
    heading_ar?: string | null;
    subheading_en?: string | null;
    subheading_ar?: string | null;
    /**
     * Enter the Vimeo video ID (e.g., "123456789")
     */
    background_video?: string | null;
    /**
     * Fallback image if video is not available
     */
    background_image?: (string | null) | Media;
    cta_text_en?: string | null;
    cta_text_ar?: string | null;
    /**
     * URL or path (e.g., "/contact" or "https://example.com")
     */
    cta_link?: string | null;
  };
  /**
   * Add flexible content sections to build your page
   */
  sections?:
    | {
        sectionType: 'richText' | 'twoColumn' | 'gallery' | 'cta' | 'custom';
        heading_en?: string | null;
        heading_ar?: string | null;
        content_en?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        content_ar?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        image?: (string | null) | Media;
        imagePosition?: ('left' | 'right') | null;
        images?:
          | {
              image: string | Media;
              caption_en?: string | null;
              caption_ar?: string | null;
              id?: string | null;
            }[]
          | null;
        cta_text_en?: string | null;
        cta_text_ar?: string | null;
        cta_link?: string | null;
        /**
         * Use with caution. HTML will be sanitized on the frontend.
         */
        customHtml?: string | null;
        backgroundColor?: ('white' | 'light-gray' | 'primary-light' | 'dark') | null;
        id?: string | null;
      }[]
    | null;
  seo?: {
    /**
     * Recommended: 50-60 characters
     */
    meta_title_en?: string | null;
    /**
     * Recommended: 50-60 characters
     */
    meta_title_ar?: string | null;
    /**
     * Recommended: 150-160 characters
     */
    meta_description_en?: string | null;
    /**
     * Recommended: 150-160 characters
     */
    meta_description_ar?: string | null;
    /**
     * Recommended size: 1200×630px for social media sharing
     */
    og_image?: (string | null) | Media;
    /**
     * Comma-separated keywords for SEO
     */
    keywords_en?: string | null;
    /**
     * Comma-separated keywords for SEO
     */
    keywords_ar?: string | null;
    /**
     * Optional: Specify the canonical URL if different from the page URL
     */
    canonical_url?: string | null;
    /**
     * Prevent search engines from indexing this page
     */
    noindex?: boolean | null;
    /**
     * Prevent search engines from following links on this page
     */
    nofollow?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Required for accessibility. Describe the image content.
   */
  alt: string;
  caption_en?: string | null;
  caption_ar?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog".
 */
export interface Blog {
  id: string;
  title_en: string;
  title_ar: string;
  /**
   * URL-friendly identifier (e.g., "my-blog-post")
   */
  slug: string;
  /**
   * Short summary for blog listing pages (150-200 characters)
   */
  excerpt_en: string;
  /**
   * Short summary for blog listing pages (150-200 characters)
   */
  excerpt_ar: string;
  content_en: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  content_ar: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Main image for the blog post (recommended: 1200×630px)
   */
  featured_image: string | Media;
  category: 'video-production' | 'industry-news' | 'case-studies' | 'tips-tutorials' | 'company-news';
  /**
   * Comma-separated tags (e.g., "video, editing, production")
   */
  tags_en?: string | null;
  /**
   * Comma-separated tags in Arabic
   */
  tags_ar?: string | null;
  /**
   * Select the author of this blog post
   */
  author: string | User;
  /**
   * The date this post was or will be published
   */
  publishedDate: string;
  status: 'draft' | 'published';
  seo?: {
    /**
     * Recommended: 50-60 characters. Defaults to post title if empty.
     */
    meta_title_en?: string | null;
    /**
     * Recommended: 50-60 characters. Defaults to post title if empty.
     */
    meta_title_ar?: string | null;
    /**
     * Recommended: 150-160 characters. Defaults to excerpt if empty.
     */
    meta_description_en?: string | null;
    /**
     * Recommended: 150-160 characters. Defaults to excerpt if empty.
     */
    meta_description_ar?: string | null;
    /**
     * Recommended size: 1200×630px. Defaults to featured image if empty.
     */
    og_image?: (string | null) | Media;
    /**
     * Optional: Specify the canonical URL if different from the post URL
     */
    canonical_url?: string | null;
    /**
     * Prevent search engines from indexing this post
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio".
 */
export interface Portfolio {
  id: string;
  title_en: string;
  title_ar: string;
  /**
   * URL-friendly identifier (e.g., "my-project")
   */
  slug: string;
  /**
   * Name of the client for this project
   */
  client: string;
  /**
   * Full project description and details
   */
  description_en: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Full project description and details
   */
  description_ar: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category: 'commercial' | 'corporate' | 'documentary' | 'animation' | 'event';
  /**
   * Full Vimeo URL (e.g., "https://vimeo.com/123456789") or just the ID
   */
  video_url: string;
  /**
   * Project thumbnail for grid display (recommended: 1280×720px, 16:9 aspect ratio)
   */
  thumbnail: string | Media;
  /**
   * Display this project on the homepage
   */
  featured?: boolean | null;
  /**
   * Lower numbers appear first (0 = highest priority)
   */
  order?: number | null;
  /**
   * When this project was completed
   */
  completedDate: string;
  seo?: {
    /**
     * Recommended: 50-60 characters. Defaults to project title if empty.
     */
    meta_title_en?: string | null;
    /**
     * Recommended: 50-60 characters. Defaults to project title if empty.
     */
    meta_title_ar?: string | null;
    /**
     * Recommended: 150-160 characters.
     */
    meta_description_en?: string | null;
    /**
     * Recommended: 150-160 characters.
     */
    meta_description_ar?: string | null;
    /**
     * Recommended size: 1200×630px. Defaults to thumbnail if empty.
     */
    og_image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  title_en: string;
  title_ar: string;
  /**
   * URL-friendly identifier (e.g., "video-production")
   */
  slug: string;
  /**
   * Short description of the service (150-200 characters)
   */
  description_en: string;
  /**
   * Short description of the service (150-200 characters)
   */
  description_ar: string;
  /**
   * Detailed service information (optional)
   */
  content_en?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Detailed service information (optional)
   */
  content_ar?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Icon or image representing this service (recommended: 200×200px)
   */
  icon?: (string | null) | Media;
  /**
   * Categorize this service for filtering
   */
  category?: ('video-production' | 'post-production' | 'animation' | 'photography' | 'consulting' | 'other') | null;
  /**
   * Display this service prominently on the homepage
   */
  featured?: boolean | null;
  /**
   * Lower numbers appear first (0 = highest priority)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: string;
  /**
   * Team member's full name
   */
  name: string;
  /**
   * Job title or role (e.g., "Creative Director")
   */
  position_en: string;
  /**
   * Job title or role in Arabic
   */
  position_ar: string;
  /**
   * Short biography (150-250 characters)
   */
  bio_en: string;
  /**
   * Short biography in Arabic (150-250 characters)
   */
  bio_ar: string;
  /**
   * Team member photo (recommended: 400×400px, square aspect ratio)
   */
  photo: string | Media;
  /**
   * Full LinkedIn profile URL (optional)
   */
  linkedin?: string | null;
  /**
   * Lower numbers appear first (0 = highest priority)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: string;
  /**
   * Name of the client or company
   */
  name: string;
  /**
   * Client logo image (recommended: max 200px width, transparent background)
   */
  logo: string | Media;
  /**
   * Client website URL (optional, e.g., "https://example.com")
   */
  website?: string | null;
  /**
   * Lower numbers appear first in the carousel (0 = highest priority)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timeline".
 */
export interface Timeline {
  id: string;
  /**
   * Year of the milestone or award (e.g., 2024)
   */
  year: number;
  /**
   * Milestone or award title (e.g., "Company Founded", "Best Video Production Award")
   */
  title_en: string;
  /**
   * Milestone or award title in Arabic
   */
  title_ar: string;
  /**
   * Brief description of the milestone or award (100-200 characters)
   */
  description_en: string;
  /**
   * Brief description of the milestone or award in Arabic (100-200 characters)
   */
  description_ar: string;
  /**
   * Categorize as a company milestone or an award received
   */
  type: 'milestone' | 'award';
  /**
   * Optional icon or image for this timeline item (recommended: 200×200px)
   */
  icon?: (string | null) | Media;
  /**
   * Lower numbers appear first (0 = highest priority). Typically ordered by year.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'blog';
        value: string | Blog;
      } | null)
    | ({
        relationTo: 'portfolio';
        value: string | Portfolio;
      } | null)
    | ({
        relationTo: 'services';
        value: string | Service;
      } | null)
    | ({
        relationTo: 'team';
        value: string | Team;
      } | null)
    | ({
        relationTo: 'clients';
        value: string | Client;
      } | null)
    | ({
        relationTo: 'timeline';
        value: string | Timeline;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title_en?: T;
  title_ar?: T;
  slug?: T;
  status?: T;
  hero?:
    | T
    | {
        heading_en?: T;
        heading_ar?: T;
        subheading_en?: T;
        subheading_ar?: T;
        background_video?: T;
        background_image?: T;
        cta_text_en?: T;
        cta_text_ar?: T;
        cta_link?: T;
      };
  sections?:
    | T
    | {
        sectionType?: T;
        heading_en?: T;
        heading_ar?: T;
        content_en?: T;
        content_ar?: T;
        image?: T;
        imagePosition?: T;
        images?:
          | T
          | {
              image?: T;
              caption_en?: T;
              caption_ar?: T;
              id?: T;
            };
        cta_text_en?: T;
        cta_text_ar?: T;
        cta_link?: T;
        customHtml?: T;
        backgroundColor?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        meta_title_en?: T;
        meta_title_ar?: T;
        meta_description_en?: T;
        meta_description_ar?: T;
        og_image?: T;
        keywords_en?: T;
        keywords_ar?: T;
        canonical_url?: T;
        noindex?: T;
        nofollow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog_select".
 */
export interface BlogSelect<T extends boolean = true> {
  title_en?: T;
  title_ar?: T;
  slug?: T;
  excerpt_en?: T;
  excerpt_ar?: T;
  content_en?: T;
  content_ar?: T;
  featured_image?: T;
  category?: T;
  tags_en?: T;
  tags_ar?: T;
  author?: T;
  publishedDate?: T;
  status?: T;
  seo?:
    | T
    | {
        meta_title_en?: T;
        meta_title_ar?: T;
        meta_description_en?: T;
        meta_description_ar?: T;
        og_image?: T;
        canonical_url?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio_select".
 */
export interface PortfolioSelect<T extends boolean = true> {
  title_en?: T;
  title_ar?: T;
  slug?: T;
  client?: T;
  description_en?: T;
  description_ar?: T;
  category?: T;
  video_url?: T;
  thumbnail?: T;
  featured?: T;
  order?: T;
  completedDate?: T;
  seo?:
    | T
    | {
        meta_title_en?: T;
        meta_title_ar?: T;
        meta_description_en?: T;
        meta_description_ar?: T;
        og_image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title_en?: T;
  title_ar?: T;
  slug?: T;
  description_en?: T;
  description_ar?: T;
  content_en?: T;
  content_ar?: T;
  icon?: T;
  category?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  name?: T;
  position_en?: T;
  position_ar?: T;
  bio_en?: T;
  bio_ar?: T;
  photo?: T;
  linkedin?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  website?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timeline_select".
 */
export interface TimelineSelect<T extends boolean = true> {
  year?: T;
  title_en?: T;
  title_ar?: T;
  description_en?: T;
  description_ar?: T;
  type?: T;
  icon?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption_en?: T;
  caption_ar?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Global site settings including contact information and social media links
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: string;
  contact: {
    /**
     * Primary contact email for the company
     */
    email: string;
    /**
     * Primary contact phone number (e.g., "+966 12 345 6789")
     */
    phone: string;
    /**
     * Full company address in English
     */
    address_en: string;
    /**
     * Full company address in Arabic
     */
    address_ar: string;
    /**
     * Google Maps embed URL for the contact page
     */
    mapUrl?: string | null;
  };
  social?: {
    /**
     * Full URL to Facebook page (e.g., "https://facebook.com/dnamedia")
     */
    facebook?: string | null;
    /**
     * Full URL to Instagram profile (e.g., "https://instagram.com/dnamedia")
     */
    instagram?: string | null;
    /**
     * Full URL to Twitter/X profile (e.g., "https://twitter.com/dnamedia")
     */
    twitter?: string | null;
    /**
     * Full URL to LinkedIn company page (e.g., "https://linkedin.com/company/dnamedia")
     */
    linkedin?: string | null;
    /**
     * Full URL to YouTube channel (e.g., "https://youtube.com/@dnamedia")
     */
    youtube?: string | null;
    /**
     * Full URL to TikTok profile (e.g., "https://tiktok.com/@dnamedia")
     */
    tiktok?: string | null;
    /**
     * Full URL to Vimeo profile (e.g., "https://vimeo.com/dnamedia")
     */
    vimeo?: string | null;
  };
  branding?: {
    /**
     * Company logo for header and footer (SVG or PNG recommended)
     */
    logo?: (string | null) | Media;
    /**
     * Alternative text for the logo (for accessibility)
     */
    logoAlt_en?: string | null;
    /**
     * Alternative text for the logo in Arabic
     */
    logoAlt_ar?: string | null;
    /**
     * Site favicon (32×32px or 64×64px PNG/ICO)
     */
    favicon?: (string | null) | Media;
  };
  seo?: {
    /**
     * Default site name for SEO (e.g., "DNA Media")
     */
    site_name_en?: string | null;
    /**
     * Default site name in Arabic
     */
    site_name_ar?: string | null;
    /**
     * Default meta description for pages without custom descriptions
     */
    site_description_en?: string | null;
    /**
     * Default meta description in Arabic
     */
    site_description_ar?: string | null;
    /**
     * Default image for social media sharing (1200×630px recommended)
     */
    og_image?: (string | null) | Media;
  };
  businessHours?: {
    /**
     * Operating hours in English (e.g., "Sunday - Thursday: 9:00 AM - 6:00 PM")
     */
    hours_en?: string | null;
    /**
     * Operating hours in Arabic
     */
    hours_ar?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        address_en?: T;
        address_ar?: T;
        mapUrl?: T;
      };
  social?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        twitter?: T;
        linkedin?: T;
        youtube?: T;
        tiktok?: T;
        vimeo?: T;
      };
  branding?:
    | T
    | {
        logo?: T;
        logoAlt_en?: T;
        logoAlt_ar?: T;
        favicon?: T;
      };
  seo?:
    | T
    | {
        site_name_en?: T;
        site_name_ar?: T;
        site_description_en?: T;
        site_description_ar?: T;
        og_image?: T;
      };
  businessHours?:
    | T
    | {
        hours_en?: T;
        hours_ar?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}