/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    pages: Page;
    blog: Blog;
    works: Work;
    team: Team;
    clients: Client;
    timeline: Timeline;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    blog: BlogSelect<false> | BlogSelect<true>;
    works: WorksSelect<false> | WorksSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    timeline: TimelineSelect<false> | TimelineSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  role: 'admin' | 'editor';
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title_en: string;
  title_ar: string;
  /**
   * URL-friendly identifier (e.g., "home", "about", "contact")
   */
  slug: string;
  status: 'draft' | 'published';
  hero?: {
    heading_en?: string | null;
    heading_ar?: string | null;
    subheading_en?: string | null;
    subheading_ar?: string | null;
    /**
     * Enter the Vimeo video ID (e.g., "123456789")
     */
    background_video?: string | null;
    /**
     * Fallback image if video is not available
     */
    background_image?: (string | null) | Media;
    cta_text_en?: string | null;
    cta_text_ar?: string | null;
    /**
     * URL or path (e.g., "/contact")
     */
    cta_link?: string | null;
  };
  /**
   * Second hero banner (used on team and about pages)
   */
  hero2?: {
    heading_en?: string | null;
    heading_ar?: string | null;
    /**
     * Enter the Vimeo video ID (e.g., "123456789")
     */
    background_video?: string | null;
    /**
     * Fallback image if video is not available
     */
    background_image?: (string | null) | Media;
  };
  /**
   * Tagline displayed below the hero on the homepage
   */
  tagline?: {
    text_en?: string | null;
    text_ar?: string | null;
    button_text_en?: string | null;
    button_text_ar?: string | null;
    button_link?: string | null;
  };
  /**
   * Showcase a featured project on the homepage
   */
  featuredWork?: {
    projectNumber?: string | null;
    serviceType_en?: string | null;
    serviceType_ar?: string | null;
    projectTitle_en?: string | null;
    projectTitle_ar?: string | null;
    /**
     * 1824×920px recommended
     */
    backgroundImage?: (string | null) | Media;
    /**
     * Optional Vimeo video ID. Video will overlay the image.
     */
    backgroundVideo?: string | null;
    projectLink?: string | null;
    soundOn_en?: string | null;
    soundOn_ar?: string | null;
    soundOff_en?: string | null;
    soundOff_ar?: string | null;
  };
  /**
   * About DNA Studio section (homepage and team page)
   */
  aboutSection?: {
    label_en?: string | null;
    label_ar?: string | null;
    heading_en?: string | null;
    heading_ar?: string | null;
    /**
     * 1368×618px recommended
     */
    image?: (string | null) | Media;
    description_en?: string | null;
    description_ar?: string | null;
  };
  /**
   * CTA section with heading and button link
   */
  ctaSection?: {
    heading_en?: string | null;
    heading_ar?: string | null;
    buttonLink?: string | null;
    /**
     * 1824×1080px recommended
     */
    backgroundImage?: (string | null) | Media;
    /**
     * 500×500px recommended
     */
    circleImage?: (string | null) | Media;
  };
  /**
   * Simple CTA banner with heading and button (shown before footer)
   */
  blogCta?: {
    heading_en?: string | null;
    heading_ar?: string | null;
    buttonLink?: string | null;
  };
  /**
   * Featured hero section at the top of the blog page
   */
  blogHero?: {
    /**
     * Main heading displayed over the hero image (supports multiple lines)
     */
    title_en?: string | null;
    title_ar?: string | null;
    /**
     * Small label shown above the title (e.g., "Topic")
     */
    topic_en?: string | null;
    topic_ar?: string | null;
    /**
     * URL for the Read More button (e.g., "/en/blog/my-post")
     */
    link?: string | null;
    /**
     * Hero background image (1824×1027px recommended). Will be displayed in grayscale.
     */
    background_image?: (string | null) | Media;
  };
  /**
   * Hero section with animated text overlay for the about page
   */
  aboutHero?: {
    /**
     * Text lines that animate over the hero image
     */
    textLines?:
      | {
          text_en: string;
          text_ar: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Heading text shown at the top of the works page
   */
  worksHeading?: {
    heading_en?: string | null;
    heading_ar?: string | null;
  };
  /**
   * Content for the contact/let's work page
   */
  contactSection?: {
    tab1_en?: string | null;
    tab1_ar?: string | null;
    tab2_en?: string | null;
    tab2_ar?: string | null;
    /**
     * Full-width background image (1920×900px recommended)
     */
    background_image?: (string | null) | Media;
    office_heading_en?: string | null;
    office_heading_ar?: string | null;
    office_address_en?: string | null;
    office_address_ar?: string | null;
    mail_heading_en?: string | null;
    mail_heading_ar?: string | null;
    emails?:
      | {
          email: string;
          id?: string | null;
        }[]
      | null;
    follow_heading_en?: string | null;
    follow_heading_ar?: string | null;
    socialLinks?:
      | {
          platform: string;
          url: string;
          id?: string | null;
        }[]
      | null;
    bottom_heading_en?: string | null;
    bottom_heading_ar?: string | null;
    form_name_label_en?: string | null;
    form_name_label_ar?: string | null;
    form_name_placeholder_en?: string | null;
    form_name_placeholder_ar?: string | null;
    form_email_label_en?: string | null;
    form_email_label_ar?: string | null;
    form_email_placeholder_en?: string | null;
    form_email_placeholder_ar?: string | null;
    form_services_label_en?: string | null;
    form_services_label_ar?: string | null;
    /**
     * Pill/tag options for services selection
     */
    services?:
      | {
          label_en: string;
          label_ar: string;
          id?: string | null;
        }[]
      | null;
    form_message_label_en?: string | null;
    form_message_label_ar?: string | null;
    form_message_placeholder_en?: string | null;
    form_message_placeholder_ar?: string | null;
    form_submit_en?: string | null;
    form_submit_ar?: string | null;
    form_submitting_en?: string | null;
    form_submitting_ar?: string | null;
  };
  seo?: {
    /**
     * 50-60 characters recommended
     */
    meta_title_en?: string | null;
    /**
     * 50-60 characters recommended
     */
    meta_title_ar?: string | null;
    /**
     * 150-160 characters recommended
     */
    meta_description_en?: string | null;
    /**
     * 150-160 characters recommended
     */
    meta_description_ar?: string | null;
    /**
     * 1200×630px recommended
     */
    og_image?: (string | null) | Media;
    /**
     * Comma-separated keywords
     */
    keywords_en?: string | null;
    /**
     * Comma-separated keywords
     */
    keywords_ar?: string | null;
    /**
     * Optional: if different from the page URL
     */
    canonical_url?: string | null;
    /**
     * Prevent search engines from indexing
     */
    noindex?: boolean | null;
    /**
     * Prevent search engines from following links
     */
    nofollow?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Required for accessibility. Describe the image content.
   */
  alt: string;
  caption_en?: string | null;
  caption_ar?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog".
 */
export interface Blog {
  id: string;
  title_en: string;
  title_ar: string;
  /**
   * URL-friendly identifier (e.g., "my-blog-post")
   */
  slug: string;
  /**
   * Short summary for blog listing pages (150-200 characters)
   */
  excerpt_en: string;
  /**
   * Short summary for blog listing pages (150-200 characters)
   */
  excerpt_ar: string;
  content_en: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  content_ar: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Main image for the blog post (recommended: 1200×630px)
   */
  featured_image: string | Media;
  category: 'video-production' | 'industry-news' | 'case-studies' | 'tips-tutorials' | 'company-news';
  /**
   * Comma-separated tags (e.g., "video, editing, production")
   */
  tags_en?: string | null;
  /**
   * Comma-separated tags in Arabic
   */
  tags_ar?: string | null;
  /**
   * Select the author of this blog post
   */
  author: string | User;
  /**
   * The date this post was or will be published
   */
  publishedDate: string;
  status: 'draft' | 'published';
  /**
   * Content for the blog detail page. Description, main heading, main image appear once. Add multiple content blocks below.
   */
  article_detail?: {
    /**
     * Introductory paragraph shown at the very top of the article
     */
    description_en?: string | null;
    description_ar?: string | null;
    /**
     * Main heading shown below the description, above the image
     */
    main_heading_en?: string | null;
    main_heading_ar?: string | null;
    /**
     * Image shown below the main heading (one time only)
     */
    main_image?: (string | null) | Media;
    /**
     * Add as many heading + paragraph sections as you need
     */
    blocks?:
      | {
          heading_en: string;
          heading_ar: string;
          paragraph_en: string;
          paragraph_ar: string;
          id?: string | null;
        }[]
      | null;
  };
  seo?: {
    /**
     * Recommended: 50-60 characters. Defaults to post title if empty.
     */
    meta_title_en?: string | null;
    /**
     * Recommended: 50-60 characters. Defaults to post title if empty.
     */
    meta_title_ar?: string | null;
    /**
     * Recommended: 150-160 characters. Defaults to excerpt if empty.
     */
    meta_description_en?: string | null;
    /**
     * Recommended: 150-160 characters. Defaults to excerpt if empty.
     */
    meta_description_ar?: string | null;
    /**
     * Recommended size: 1200×630px. Defaults to featured image if empty.
     */
    og_image?: (string | null) | Media;
    /**
     * Optional: Specify the canonical URL if different from the post URL
     */
    canonical_url?: string | null;
    /**
     * Prevent search engines from indexing this post
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works".
 */
export interface Work {
  id: string;
  project_en: string;
  project_ar: string;
  /**
   * URL-friendly identifier (e.g., "my-project")
   */
  slug: string;
  industry_en: string;
  industry_ar: string;
  /**
   * Project description shown on the detail page
   */
  description_en?: string | null;
  description_ar?: string | null;
  /**
   * Square image recommended (896×896px). Used in the works grid.
   */
  image: string | Media;
  order?: number | null;
  status: 'draft' | 'published';
  /**
   * Videos shown in the horizontal carousel on the detail page
   */
  videos?:
    | {
        url: string;
        thumbnail?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  credits?: {
    client_en?: string | null;
    client_ar?: string | null;
    agency_en?: string | null;
    agency_ar?: string | null;
    director_en?: string | null;
    director_ar?: string | null;
    dop_en?: string | null;
    dop_ar?: string | null;
    executiveProducer_en?: string | null;
    executiveProducer_ar?: string | null;
    industry_en?: string | null;
    industry_ar?: string | null;
  };
  seo?: {
    meta_title_en?: string | null;
    meta_title_ar?: string | null;
    meta_description_en?: string | null;
    meta_description_ar?: string | null;
    og_image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: string;
  /**
   * Team member's full name
   */
  name: string;
  /**
   * Job title or role (e.g., "Creative Director")
   */
  position_en: string;
  /**
   * Job title or role in Arabic
   */
  position_ar: string;
  /**
   * Short biography (150-250 characters)
   */
  bio_en: string;
  /**
   * Short biography in Arabic (150-250 characters)
   */
  bio_ar: string;
  /**
   * Team member photo (recommended: 400×400px, square aspect ratio)
   */
  photo: string | Media;
  /**
   * Full LinkedIn profile URL (optional)
   */
  linkedin?: string | null;
  /**
   * Lower numbers appear first (0 = highest priority)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: string;
  /**
   * Name of the client or company
   */
  name: string;
  /**
   * Client logo image (recommended: max 200px width, transparent background)
   */
  logo: string | Media;
  /**
   * Client website URL (optional, e.g., "https://example.com")
   */
  website?: string | null;
  /**
   * Lower numbers appear first in the carousel (0 = highest priority)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timeline".
 */
export interface Timeline {
  id: string;
  /**
   * Year of the milestone or award (e.g., 2024)
   */
  year: number;
  /**
   * Milestone or award title (e.g., "Company Founded", "Best Video Production Award")
   */
  title_en: string;
  /**
   * Milestone or award title in Arabic
   */
  title_ar: string;
  /**
   * Brief description of the milestone or award (100-200 characters)
   */
  description_en: string;
  /**
   * Brief description of the milestone or award in Arabic (100-200 characters)
   */
  description_ar: string;
  /**
   * Categorize as a company milestone or an award received
   */
  type: 'milestone' | 'award';
  /**
   * Optional icon or image for this timeline item (recommended: 200×200px)
   */
  icon?: (string | null) | Media;
  /**
   * Lower numbers appear first (0 = highest priority). Typically ordered by year.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'blog';
        value: string | Blog;
      } | null)
    | ({
        relationTo: 'works';
        value: string | Work;
      } | null)
    | ({
        relationTo: 'team';
        value: string | Team;
      } | null)
    | ({
        relationTo: 'clients';
        value: string | Client;
      } | null)
    | ({
        relationTo: 'timeline';
        value: string | Timeline;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title_en?: T;
  title_ar?: T;
  slug?: T;
  status?: T;
  hero?:
    | T
    | {
        heading_en?: T;
        heading_ar?: T;
        subheading_en?: T;
        subheading_ar?: T;
        background_video?: T;
        background_image?: T;
        cta_text_en?: T;
        cta_text_ar?: T;
        cta_link?: T;
      };
  hero2?:
    | T
    | {
        heading_en?: T;
        heading_ar?: T;
        background_video?: T;
        background_image?: T;
      };
  tagline?:
    | T
    | {
        text_en?: T;
        text_ar?: T;
        button_text_en?: T;
        button_text_ar?: T;
        button_link?: T;
      };
  featuredWork?:
    | T
    | {
        projectNumber?: T;
        serviceType_en?: T;
        serviceType_ar?: T;
        projectTitle_en?: T;
        projectTitle_ar?: T;
        backgroundImage?: T;
        backgroundVideo?: T;
        projectLink?: T;
        soundOn_en?: T;
        soundOn_ar?: T;
        soundOff_en?: T;
        soundOff_ar?: T;
      };
  aboutSection?:
    | T
    | {
        label_en?: T;
        label_ar?: T;
        heading_en?: T;
        heading_ar?: T;
        image?: T;
        description_en?: T;
        description_ar?: T;
      };
  ctaSection?:
    | T
    | {
        heading_en?: T;
        heading_ar?: T;
        buttonLink?: T;
        backgroundImage?: T;
        circleImage?: T;
      };
  blogCta?:
    | T
    | {
        heading_en?: T;
        heading_ar?: T;
        buttonLink?: T;
      };
  blogHero?:
    | T
    | {
        title_en?: T;
        title_ar?: T;
        topic_en?: T;
        topic_ar?: T;
        link?: T;
        background_image?: T;
      };
  aboutHero?:
    | T
    | {
        textLines?:
          | T
          | {
              text_en?: T;
              text_ar?: T;
              id?: T;
            };
      };
  worksHeading?:
    | T
    | {
        heading_en?: T;
        heading_ar?: T;
      };
  contactSection?:
    | T
    | {
        tab1_en?: T;
        tab1_ar?: T;
        tab2_en?: T;
        tab2_ar?: T;
        background_image?: T;
        office_heading_en?: T;
        office_heading_ar?: T;
        office_address_en?: T;
        office_address_ar?: T;
        mail_heading_en?: T;
        mail_heading_ar?: T;
        emails?:
          | T
          | {
              email?: T;
              id?: T;
            };
        follow_heading_en?: T;
        follow_heading_ar?: T;
        socialLinks?:
          | T
          | {
              platform?: T;
              url?: T;
              id?: T;
            };
        bottom_heading_en?: T;
        bottom_heading_ar?: T;
        form_name_label_en?: T;
        form_name_label_ar?: T;
        form_name_placeholder_en?: T;
        form_name_placeholder_ar?: T;
        form_email_label_en?: T;
        form_email_label_ar?: T;
        form_email_placeholder_en?: T;
        form_email_placeholder_ar?: T;
        form_services_label_en?: T;
        form_services_label_ar?: T;
        services?:
          | T
          | {
              label_en?: T;
              label_ar?: T;
              id?: T;
            };
        form_message_label_en?: T;
        form_message_label_ar?: T;
        form_message_placeholder_en?: T;
        form_message_placeholder_ar?: T;
        form_submit_en?: T;
        form_submit_ar?: T;
        form_submitting_en?: T;
        form_submitting_ar?: T;
      };
  seo?:
    | T
    | {
        meta_title_en?: T;
        meta_title_ar?: T;
        meta_description_en?: T;
        meta_description_ar?: T;
        og_image?: T;
        keywords_en?: T;
        keywords_ar?: T;
        canonical_url?: T;
        noindex?: T;
        nofollow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog_select".
 */
export interface BlogSelect<T extends boolean = true> {
  title_en?: T;
  title_ar?: T;
  slug?: T;
  excerpt_en?: T;
  excerpt_ar?: T;
  content_en?: T;
  content_ar?: T;
  featured_image?: T;
  category?: T;
  tags_en?: T;
  tags_ar?: T;
  author?: T;
  publishedDate?: T;
  status?: T;
  article_detail?:
    | T
    | {
        description_en?: T;
        description_ar?: T;
        main_heading_en?: T;
        main_heading_ar?: T;
        main_image?: T;
        blocks?:
          | T
          | {
              heading_en?: T;
              heading_ar?: T;
              paragraph_en?: T;
              paragraph_ar?: T;
              id?: T;
            };
      };
  seo?:
    | T
    | {
        meta_title_en?: T;
        meta_title_ar?: T;
        meta_description_en?: T;
        meta_description_ar?: T;
        og_image?: T;
        canonical_url?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works_select".
 */
export interface WorksSelect<T extends boolean = true> {
  project_en?: T;
  project_ar?: T;
  slug?: T;
  industry_en?: T;
  industry_ar?: T;
  description_en?: T;
  description_ar?: T;
  image?: T;
  order?: T;
  status?: T;
  videos?:
    | T
    | {
        url?: T;
        thumbnail?: T;
        title?: T;
        id?: T;
      };
  credits?:
    | T
    | {
        client_en?: T;
        client_ar?: T;
        agency_en?: T;
        agency_ar?: T;
        director_en?: T;
        director_ar?: T;
        dop_en?: T;
        dop_ar?: T;
        executiveProducer_en?: T;
        executiveProducer_ar?: T;
        industry_en?: T;
        industry_ar?: T;
      };
  seo?:
    | T
    | {
        meta_title_en?: T;
        meta_title_ar?: T;
        meta_description_en?: T;
        meta_description_ar?: T;
        og_image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  name?: T;
  position_en?: T;
  position_ar?: T;
  bio_en?: T;
  bio_ar?: T;
  photo?: T;
  linkedin?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  website?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timeline_select".
 */
export interface TimelineSelect<T extends boolean = true> {
  year?: T;
  title_en?: T;
  title_ar?: T;
  description_en?: T;
  description_ar?: T;
  type?: T;
  icon?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption_en?: T;
  caption_ar?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Global site settings — contact, social, branding, navigation, footer
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: string;
  contact: {
    /**
     * Primary contact email
     */
    email: string;
    /**
     * e.g., "+966 12 345 6789"
     */
    phone: string;
    address_en: string;
    address_ar: string;
    mapUrl?: string | null;
  };
  social?: {
    facebook?: string | null;
    instagram?: string | null;
    twitter?: string | null;
    linkedin?: string | null;
    youtube?: string | null;
    tiktok?: string | null;
    vimeo?: string | null;
  };
  branding?: {
    /**
     * SVG or PNG recommended
     */
    logo?: (string | null) | Media;
    logoAlt_en?: string | null;
    logoAlt_ar?: string | null;
    /**
     * 32×32px or 64×64px PNG/ICO
     */
    favicon?: (string | null) | Media;
  };
  seo?: {
    site_name_en?: string | null;
    site_name_ar?: string | null;
    /**
     * Fallback meta description
     */
    site_description_en?: string | null;
    site_description_ar?: string | null;
    /**
     * 1200×630px recommended
     */
    og_image?: (string | null) | Media;
  };
  businessHours?: {
    /**
     * e.g., "Sunday - Thursday: 9:00 AM - 6:00 PM"
     */
    hours_en?: string | null;
    hours_ar?: string | null;
  };
  navigation?: {
    menuItems?:
      | {
          label_en: string;
          label_ar: string;
          description_en?: string | null;
          description_ar?: string | null;
          /**
           * Relative URL without language prefix (e.g., "/about")
           */
          url: string;
          /**
           * Lower numbers appear first
           */
          order: number;
          id?: string | null;
        }[]
      | null;
  };
  footer?: {
    office_heading_en?: string | null;
    office_heading_ar?: string | null;
    mail_heading_en?: string | null;
    mail_heading_ar?: string | null;
    follow_heading_en?: string | null;
    follow_heading_ar?: string | null;
    emails?:
      | {
          /**
           * e.g., "General Inquiries"
           */
          label?: string | null;
          email: string;
          id?: string | null;
        }[]
      | null;
    socialLinks?:
      | {
          platform: string;
          url: string;
          id?: string | null;
        }[]
      | null;
    copyright_en?: string | null;
    copyright_ar?: string | null;
    terms_en?: string | null;
    terms_ar?: string | null;
    terms_link?: string | null;
    /**
     * 1908×213px recommended
     */
    background_image?: (string | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        address_en?: T;
        address_ar?: T;
        mapUrl?: T;
      };
  social?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        twitter?: T;
        linkedin?: T;
        youtube?: T;
        tiktok?: T;
        vimeo?: T;
      };
  branding?:
    | T
    | {
        logo?: T;
        logoAlt_en?: T;
        logoAlt_ar?: T;
        favicon?: T;
      };
  seo?:
    | T
    | {
        site_name_en?: T;
        site_name_ar?: T;
        site_description_en?: T;
        site_description_ar?: T;
        og_image?: T;
      };
  businessHours?:
    | T
    | {
        hours_en?: T;
        hours_ar?: T;
      };
  navigation?:
    | T
    | {
        menuItems?:
          | T
          | {
              label_en?: T;
              label_ar?: T;
              description_en?: T;
              description_ar?: T;
              url?: T;
              order?: T;
              id?: T;
            };
      };
  footer?:
    | T
    | {
        office_heading_en?: T;
        office_heading_ar?: T;
        mail_heading_en?: T;
        mail_heading_ar?: T;
        follow_heading_en?: T;
        follow_heading_ar?: T;
        emails?:
          | T
          | {
              label?: T;
              email?: T;
              id?: T;
            };
        socialLinks?:
          | T
          | {
              platform?: T;
              url?: T;
              id?: T;
            };
        copyright_en?: T;
        copyright_ar?: T;
        terms_en?: T;
        terms_ar?: T;
        terms_link?: T;
        background_image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}